"use client";

import { useState, useEffect } from "react";
import { useAuth } from "../../context/AuthContext";
import Link from "next/link";
import { useParams } from "next/navigation";
import { jsPDF } from "jspdf";

export default function DocumentResultPage() {
  const { user } = useAuth();
  const params = useParams();
  const id = params.id;
  const [isDownloading, setIsDownloading] = useState(false);

  // Mock data based on ID
  const mockData: any = {
    "1": { name: "Quarterly_Report.pdf", score: 92, summary: "Strong financial growth across all sectors. Key highlights include a 15% increase in net profit and 20% reduction in operational costs.", entities: ["$4.2M Revenue", "Tech Division", "Q3 Growth"], date: "2026-01-19" },
    "2": { name: "Invoices_Batch_A.zip", score: 85, summary: "Batch processing complete. 45 invoices validated successfully. 2 flagged for further manual review due to signature mismatch.", entities: ["45 Files", "2 Anomalies", "Total: $128,400"], date: "2026-01-18" },
    "3": { name: "Contract_Draft_v2.docx", score: 78, summary: "Legal draft analysis. Identified 3 potential risk clauses regarding intellectual property and 1 ambiguity in the termination section.", entities: ["IP Clause", "Termination", "Risk: Medium"], date: "2026-01-15" },
  };

  const data = mockData[id as string] || mockData["1"];

  const handleDownload = () => {
    setIsDownloading(true);
    try {
      const doc = new jsPDF({
        orientation: 'p',
        unit: 'mm',
        format: 'a4'
      });

      // Add Branding
      doc.setFontSize(22);
      doc.setTextColor(99, 102, 241); // Accent primary color
      doc.text("AI AGENT BUILDER SYSTEM", 20, 30);

      doc.setFontSize(16);
      doc.setTextColor(0, 0, 0);
      doc.text("ANALYSIS REPORT", 20, 42);

      doc.setDrawColor(99, 102, 241);
      doc.setLineWidth(0.5);
      doc.line(20, 48, 190, 48);

      // Document Info
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text(`Document: ${data.name}`, 20, 60);
      doc.text(`Date: ${data.date}`, 20, 70);
      doc.text(`AI Confidence: ${data.score}%`, 20, 80);
      doc.text(`Identified User: ${user?.name || 'Vinay Babannavar'}`, 20, 90);

      // Executive Summary
      doc.setFontSize(14);
      doc.text("EXECUTIVE SUMMARY", 20, 110);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      const splitSummary = doc.splitTextToSize(data.summary, 170);
      doc.text(splitSummary, 20, 120);

      // Key Extractions
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("KEY EXTRACTIONS", 20, 150);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      data.entities.forEach((ent: string, index: number) => {
        doc.text(`- ${ent}`, 25, 160 + (index * 8));
      });

      // Footer
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text("Generated by AI Agent Builder System (c) 2026", 20, 280);

      // Direct Open Trigger
      const pdfBlob = doc.output('blob');
      const blobUrl = URL.createObjectURL(pdfBlob);

      // Open in new tab
      window.open(blobUrl, '_blank');

      // Note: We don't revoke immediately so the user can see/save it
      console.log("PDF opened in new tab");

    } catch (err) {
      console.error("PDF Export failed:", err);
      alert("PDF generation failed. Please check your browser permissions.");
    } finally {
      setTimeout(() => setIsDownloading(false), 1500);
    }
  };

  return (
    <div className="result-container fade-in">
      <div className="perspective">
        <div className="glass-card result-main-card slide-up">
          <div className="result-header">
            <Link href="/dashboard/history" className="back-link">← Back to History</Link>
            <div className="title-section">
              <h1 className="result-title"><span className="gradient-text">Analysis</span> Result</h1>
              <span className="doc-badge glass">{data.name}</span>
            </div>
          </div>

          <div className="result-grid">
            <div className="insight-card glass zoom-in">
              <div className="score-ring">
                <svg viewBox="0 0 36 36" className="circular-chart">
                  <path className="circle-bg" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
                  <path className="circle" strokeDasharray={`${data.score}, 100`} d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
                  <text x="18" y="20.35" className="percentage">{data.score}%</text>
                </svg>
                <p>AI Confidence</p>
              </div>
              <div className="summary-section">
                <h3>Executive Summary</h3>
                <p>{data.summary}</p>
              </div>
            </div>

            <div className="entity-card glass zoom-in">
              <h3>Key Extractions</h3>
              <div className="entity-list">
                {data.entities.map((ent: string, i: number) => (
                  <div key={i} className="entity-item glass">
                    <span className="entity-icon">🔍</span>
                    {ent}
                  </div>
                ))}
              </div>
              <button
                onClick={handleDownload}
                className={`btn-premium w-full mt-auto ${isDownloading ? 'loading' : ''}`}
                disabled={isDownloading}
              >
                {isDownloading ? "Preparing PDF..." : "View Report"}
              </button>
            </div>
          </div>
        </div>
      </div>

      <style jsx>{`
        .result-container {
          padding: 4rem 2rem;
          max-width: 1100px;
          margin: 0 auto;
        }
        .result-main-card {
          padding: 3rem;
        }
        .result-header {
          margin-bottom: 3rem;
          text-align: left;
        }
        .back-link {
          color: var(--text-secondary);
          text-decoration: none;
          font-size: 0.9rem;
          margin-bottom: 1.5rem;
          display: inline-block;
        }
        .title-section {
          display: flex;
          justify-content: space-between;
          align-items: center;
        }
        .result-title {
          font-size: 2.5rem;
          margin: 0;
        }
        .doc-badge {
          padding: 0.5rem 1rem;
          border-radius: 20px;
          font-size: 0.9rem;
          color: var(--accent-secondary);
          border: 1px solid var(--accent-secondary);
        }
        .result-grid {
          display: grid;
          grid-template-columns: 1.5fr 1fr;
          gap: 2rem;
        }
        .insight-card, .entity-card {
          padding: 2.5rem;
          border-radius: 24px;
          display: flex;
          flex-direction: column;
        }
        .score-ring {
          text-align: center;
          margin-bottom: 2rem;
        }
        .circular-chart {
          display: block;
          margin: 0 auto 1rem;
          max-width: 120px;
          max-height: 120px;
        }
        .circle-bg {
          fill: none;
          stroke: rgba(255, 255, 255, 0.05);
          stroke-width: 3.8;
        }
        .circle {
          fill: none;
          stroke: var(--accent-primary);
          stroke-width: 2.8;
          stroke-linecap: round;
        }
        .percentage {
          fill: white;
          font-family: 'Outfit', sans-serif;
          font-size: 0.5rem;
          text-anchor: middle;
          font-weight: 800;
        }
        .summary-section h3 {
          font-size: 1.4rem;
          margin-bottom: 1rem;
        }
        .summary-section p {
          color: var(--text-secondary);
          line-height: 1.6;
        }
        .entity-card h3 {
          margin-bottom: 1.5rem;
        }
        .entity-list {
          display: flex;
          flex-direction: column;
          gap: 1rem;
          margin-bottom: 2rem;
        }
        .entity-item {
          padding: 1rem;
          border-radius: 12px;
          font-size: 0.95rem;
          display: flex;
          align-items: center;
          gap: 1rem;
        }
        .entity-icon {
          font-size: 1.2rem;
          filter: drop-shadow(0 0 5px var(--accent-primary));
        }
        .w-full { width: 100%; }
        .mt-auto { margin-top: auto; }
        @media (max-width: 768px) {
          .result-grid { grid-template-columns: 1fr; }
          .title-section { flex-direction: column; align-items: flex-start; gap: 1rem; }
        }
      `}</style>
    </div>
  );
}